name: ci

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.3"
          cache: true

      # make clean build allows to re-generate the generated files (validate/validate.pb.go).
      - name: Build the current binary
        run: make clean build

      # Format all non-generated source files.
      - name: Format source files
        run: make format

      # Check the generated files consistency and source code files format.
      - name: Check consistency
        run: make check

      # Run tests.
      - name: Test
        run: make harness

      - name: Build and test using bazel
        run: make bazel-build harness test
